### ISSUE TITLE
velocity_to_value_ratio 

### ISSUE THREAD

**Issue by elthef** [ROBOTIS-GIT/dynamixel-workbench#101]
Can I find out how to derive the velocity_to_value_ratio value say for MX64 which is 86.81.
Thank you and best regards
Edwin

**Comment by routiful** [comment]
Hi :)

The RPM calculation of MX-64 is 0.11RPM * Present Speed. [REF](http://emanual.robotis.com/docs/en/dxl/mx/mx-64/#present-speed)

If this unit value convert to rad/sec,  we can get 0.01151917305 rad/sec.
A reciprocal of the number is 86.81. So i can use it to calculate value of speed for input value of Moving Speed or number of rad/sec.

Thanks 
Darby
