### ISSUE TITLE
dynamic_reconfigure servo position  limits for RX24F and XM430?

### ISSUE THREAD

**Issue by Angit16** [ROBOTIS-GIT/dynamixel-workbench#125]
Hi,
I am using `dynamixel-workbench` in ROS and want to be able to reconfigure the position limits of the servo. Will it work for `dynmic_reconfigure` with existing package?
I could not find any configuration file existing in this package. Should I need to write a `.cfg` file?

**Comment by routiful** [comment]
Hi :)

We have not support `.cfg` file. If you need it, you make it your own

Thanks
Darby

**Comment by routiful** [comment]
This issue will be closed since there were no actions for a while.
You can reopen this issue to show this issue to the users whenever.
Thanks. :)
