### ISSUE TITLE
rostopic can't return the motors' state?

### ISSUE THREAD

**Issue by ynfei** [ROBOTIS-GIT/dynamixel-workbench#133]
i use the dynamixel-workbench position control, when i want to return the motors' state ,i use this rostopic echo /dynamixel_state ,but i get this:
dynamixel_state: 
  - 
    model_name: "MX-106"
    id: 1
    torque_enable: 0
    goal_current: 0
    goal_velocity: 0
    goal_position: 0
    present_current: 0
    present_velocity: 0
    present_position: 0
    moving: 0
  - 
    model_name: "MX-64"
    id: 2
    torque_enable: 0
    goal_current: 0
    goal_velocity: 0
    goal_position: 0
    present_current: 0
    present_velocity: 0
    present_position: 0
    moving: 0
  - 
    model_name: "MX-28"
    id: 3
    torque_enable: 0
    goal_current: 0
    goal_velocity: 0
    goal_position: 0
    present_current: 0
    present_velocity: 0
    present_position: 0
    moving: 0
how could i fix this problem ,thank you!

**Comment by routiful** [comment]
Hi :)

Did you check baud rate of Dynamixel?

**Comment by routiful** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
