### ISSUE TITLE
rostopic for velocity_control?

### ISSUE THREAD

**Issue by jannsta1** [ROBOTIS-GIT/dynamixel-workbench#135]
I'm using dynamixel servos for a visual servoing project and I wanted to implement a velocity based controller for pan / tilt actions. 

I notice that the dynamixel-workbench only provides a service for setting the motor velocity rather than a topic (which I think would more commonly be used when sending a control input at a relatively high rate). I was wondering if my assumption about there only being a service for this is correct? If so are any plans to include topics as a means of setting servo velocity in future?

**Comment by routiful** [comment]
I agree with your suggestion.
I add it in TODO list(#131 ).

Thanks
