### ISSUE TITLE
Can you help me on how to control two or more Dynamixel XM-430 motors in a single command using dynamixel_workbench?

### ISSUE THREAD

**Issue by Sumilsood** [ROBOTIS-GIT/dynamixel-workbench#137]
I am currently using ROS-Kinetic. I want to do position control of two or more Dynamixel XM-430 motors using a single command in dynamixel_workbench. I hope you can help me with this.
Thank you

**Comment by routiful** [comment]
Hi :)

You can make node that has service or topic to command connected Dynamixels.
This code might be help you 

https://github.com/ROBOTIS-GIT/open_manipulator/blob/master/open_manipulator_dynamixel_ctrl/src/dynamixel_controller.cpp

Thanks

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
