### ISSUE TITLE
rosrun dynamixel_workbench_single_manager_gui dynamixel_workbench_single_manager_gui [rospack] Error: package 'dynamixel_workbench_single_manager_gui' not found

### ISSUE THREAD

**Issue by hdq123** [ROBOTIS-GIT/dynamixel-workbench#139]

**Comment by robotpilot** [comment]
Thanks. But the way you ask is wrong. There are no contents, and we don't know how to solve this issue with only the title you handed over to us. I will close this issue. If you want a more accurate answer, please create a new issue.
