### ISSUE TITLE
Arduino - dynamixel_workbench missing keywords.txt file

### ISSUE THREAD

**Issue by KurtE** [ROBOTIS-GIT/dynamixel-workbench#143]
Not sure if this is the proper place to mention it.  

But was noticing on a discussion up on the ROBOTIS forum, that many of the dynamixel_workbench methods were not showing up in the Arduino IDE as methods or special keywords... 

Looks like there is no keywords.txt file for this library, so only those that methods like ping where are in other libraries like dynamixel_sdk show up with the proper color coding.

**Comment by routiful** [comment]
Hi :)

Thank you for your inquiry. 
I updated keywords.txt file to develop branch in [OpenCR](https://github.com/ROBOTIS-GIT/OpenCR/tree/develop/arduino/opencr_arduino/opencr/libraries/DynamixelWorkbench) and [OpenCM9.04 ](https://github.com/ROBOTIS-GIT/OpenCM9.04/tree/develop/arduino/opencm_arduino/opencm9.04/libraries/DynamixelWorkbench)repo.
It will be merged master branch soon.

**Comment by KurtE** [comment]
Thanks
