### ISSUE TITLE
AX-12+ Velocity Controller

### ISSUE THREAD

**Issue by Gabry993** [ROBOTIS-GIT/dynamixel-workbench#146]
Hi,
I am trying to implement a velocity controller for two AX-12+ servos.
I started by following that tutorial
[http://wiki.ros.org/dynamixel_workbench_controllers/Tutorials/VelocityControl](url)
but it wasn't working. I read somewhere that the provided code does not apply to my servos model, but I managed to adapt it and to make it work.
The servos started to move, but only in one direction.
I found out that the problem is in that part of the code from the velocity_control.cpp:
```
{
static int32_t goal_velocity[2] = {0, 0};
goal_velocity[0] = dxl_wb_->convertVelocity2Value(dxl_id_[0], req.left_vel);
goal_velocity[1] = dxl_wb_->convertVelocity2Value(dxl_id_[1], (-1) * req.right_vel);
bool ret = dxl_wb_->syncWrite("Goal_Velocity", goal_velocity);
res.result = ret;
}

```
 The problem is that `convertVelocity2Value` does not return value suitable for my servos: it returns negative values for negative speed, while the AX-12+ moving speed is in the range 0~2047.
So, is there a convertVelocity2Value method suitable for this kind of servo? If not, is there a correspondence between speed expressed in rad/s and the values for my servos, so that I can write the method myself?

Another question: if I set a speed which is too low, the servo won't move (let's say 50 in the 0~2047 range). Is this a limitation of that model or is there something I can change to allow slow speed movements?

Thank you!
Gabriele

**Comment by routiful** [comment]
Hi :) 

Velocity controller is suitable to Dynamixel with Protocol 2.0. But you can modified it to your AX(This motor is applied Protocol 1.0).

You can check that how to velocity control for AX to follow this link. The reason why your motor is turned in one direction is `Moving Speed` address has different method to control motor.

http://emanual.robotis.com/docs/en/dxl/ax/ax-12a/#moving-speed-32

I give you a sample code how to manage it. It is included dynamixel_workbench_toolbox.

https://github.com/ROBOTIS-GIT/dynamixel-workbench/blob/master/dynamixel_workbench_toolbox/src/dynamixel_workbench_toolbox/dynamixel_workbench.cpp#L311

Thanks

**Comment by Gabry993** [comment]
Hi,
thank you very much for your answer, is exactly what I need! I thought there may be something in the toolbox, but wasn't able to find it.
Anyway, I've already seen the documentation of the servo, but I can't understand that part:
> In Wheel Mode, only the output control is possible, not speed.
> For example, if it is set to 512, it means the output is controlled by 50% of the maximum output.
My problem is that I would like to be able to set a speed in rad/s and move the servo at that speed. 
Is that possible? Is there any correspondence between a speed expressed in radians/seconds and the values I can effectively write in the register?
Finally, when setting the speed to a low value (usually in the range 1-70) the servo won't move and will start to beep. Is that a limitation of that servo or is it supposed to move anyway?

Thank you again for your help!

**Comment by AchmadFathoni** [comment]
I have tried the tutorial on emanual[emanual](http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_workbench/#tutorials) using AX-18A and failed only at Velocity and Torque control. If these two only works with Protocol 2.0 then somebody need to put a warn on the tutorial.

**Comment by routiful** [comment]
Hi, sorry for late reply.

AX series are not be able set a speed because it does not have encoder for 360 degree. You can only apply proportional voltage to operate motor. If you want to control velocity, I recommend to use [X-series](http://emanual.robotis.com/docs/en/dxl/x/xl430-w250/).

@AchmadFathoni 
Sorry for inconvenience. I am going to add warning message on tutorial for Velocity controller. But tutorial for Torque controller already had.

http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_workbench/#torque-controller

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
