### ISSUE TITLE
/cmd_vel is not working in velocity_control

### ISSUE THREAD

**Issue by mezl** [ROBOTIS-GIT/dynamixel-workbench#159]
hi, I tried tutorial ["Dynamixel workbench velocity controller with wheel command"](http://wiki.ros.org/dynamixel_workbench_controllers/Tutorials/VelocityControl) and it worked.

I am able to use "rosservice call /wheel_command 1 1" to move the robot.

The problems when I want to use /cmd_vel to move the robot but it's not working.

I check the source of [velocity_control.cpp](https://github.com/ROBOTIS-GIT/dynamixel-workbench/blob/master/dynamixel_workbench_controllers/src/velocity_control.cpp) 
The code has `void VelocityControl::commandVelocityCallback` so it should able to take /cmd_vel as well.

1. Which distro of ROS have you installed? (ex, indigo, kinetic, melodic)
Kinetic
2. Which OS have you installed? (ex, Ubuntu 16.04 LTS (Xenial Xerus), Linux Mint 18.x, ...)
Ubuntu 16.04 on RPi3
3. Which Dynamixel have you used? (ex, MX-28, XM430-W350, ...)
XL430-W250 
4. Write down the commands you used in order
I follow the instruction here.
http://wiki.ros.org/dynamixel_workbench_controllers/Tutorials/VelocityControl
  ```
roslaunch my_dynamixel_workbench_tutorial velocity_control.launch
SUMMARY
========

PARAMETERS
 * /baud_rate: 115200
 * /device_name: /dev/ttyUSB0
 * /left_wheel: 1
 * /profile_acceleration: 50
 * /profile_velocity: 200
 * /right_wheel: 2
 * /rosdistro: kinetic
 * /rosversion: 1.12.13
 * /wheel_radius: 0.033
 * /wheel_separation: 0.16

NODES
  /
    velocity_control (dynamixel_workbench_controllers/velocity_control)

auto-starting new master
process[master]: started with pid [20785]
ROS_MASTER_URI=http://pi-kai.local:11311

setting /run_id to c63a9d28-79e4-11e8-805a-b827eb58628c
process[rosout-1]: started with pid [20800]
started core service [/rosout]
process[velocity_control-2]: started with pid [20808]
-----------------------------------------------------------------------
        dynamixel_workbench controller; velocity control example       
              -This example supports MX2.0 and X Series-               
-----------------------------------------------------------------------

MODEL   : XL430-W250
ID      : 1

MODEL   : XL430-W250
ID      : 2

  ```
 
5. Copy and Paste your error message on terminal

  ```


(xenial)kai@localhost:~$ rostopic pub /cmd_vel geometry_msgs/Twist "linear:
  x: 1.0
  y: 0.0
  z: 0.0
angular:
  x: 0.0
  y: 0.0
  z: 0.0" 
publishing and latching message. Press ctrl-C to terminate
```
  
6. Please, describe detailedly what difficulty you are in 

    rostopic pub /cmd_vel  is not working for  velocity_control

**Comment by routiful** [comment]
Hi @mezl :)

Because of limitation of velocity, you didn't operate Dynamixels 
As you see, the arguments in [velocity_control.launch](https://github.com/ROBOTIS-GIT/dynamixel-workbench/blob/master/dynamixel_workbench_controllers/launch/velocity_control.launch#L8) was set. This numbers depend on TurtleBot3.

So you are supposed to publish linear velocity up to 0.22 and angular velocity up to 2.84.
The references is here

https://github.com/ROBOTIS-GIT/turtlebot3/tree/master/turtlebot3_teleop

Thanks

**Comment by mezl** [comment]
hi @routiful ,
Thanks for the reply, it works when I set Linear.X to 0.1. I had couple extend question about this.

1. Where does this 0.22 limit in linear velocity coming from? In the velocity_control.launch, there is no such setting about velocity limit.

2. When I use "rosservice call /wheel_command 1 1", both wheels are moving in the same direction(as TB3 setup). However, when I send /cmd_vel , linear.x = 0.1 will cause one wheel forward and one wheel backward. How to flip one motor direction when using /cmd_vel?

3. I notice there is "Present_Position" available in the /dynamixel_state topic, does any pre-exist package that can compute Odometry data("/odom") using this information?

Thanks

**Comment by routiful** [comment]
1. `Goal Velocity` address has limitation. I attached related references.
http://emanual.robotis.com/docs/en/dxl/x/xl430-w250/#goal-velocity104

2. Dynamixel X series provide `Drive Mode`. This function makes assembled Dynamixels are operated same directions with same value.
http://emanual.robotis.com/docs/en/dxl/x/xl430-w250/#drive-mode10

3. We don't have pre-exist package for calculating odometry. But I can give you related references to help you. This code shows how to compute odometry to use Dynamixels

https://github.com/ROBOTIS-GIT/OpenCR/blob/master/arduino/opencr_arduino/opencr/libraries/turtlebot3/examples/turtlebot3_burger/turtlebot3_core/turtlebot3_core.ino#L428

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.

**Comment by mezl** [comment]
hi routiful,
Thanks for the help. I ported the odometry code from open-cr to this package.
Now in the velocity_control.h, it can publish both /odom and odom_tf.

I also found one bug that causes wheelCommand and /cmd_vel acting differently because 
in Line 140: velocity_control.cpp
goal_velocity[1] = dxl_wb_->convertVelocity2Value(dxl_id_[1], (-1) * req.right_vel);
Howerver,  there is also a line flip the motor direction "Drive_Mode"
dxl_wb_->itemWrite(dxl_id_[1], "Drive_Mode", 1);
This will cause wheelCommand will move both motor in the same direction but /cmd_vel one move forward and one backward.

I think odom info might be useful for someone wants to use this package as diff_controller
Here is the code I updated.

https://github.com/mezl/dynamixel-workbench/commit/5442250e655ed9e371b60439975cd52087449834#diff-09637a340d630ca4a6c211bbe302d03c
https://github.com/mezl/dynamixel-workbench/commit/50a09431a57d720eaa5f2f3c0eaf72baa37fcfcc#diff-142f5f625a3f5a06ab40997368634e7c
Also add tf package in CMakelist.txt

Best,

**Comment by routiful** [comment]
Oops, My mistake. Thank you for your contribution.
If you want, you can request your code into this repository by using `Pull Request`.

Odom is important information to mobile robot but not necessary to control Dynamixel. Because this example provides how to control Dynamixel is set velocity control mode in ROS, I think odom is not needed to this example.
I appreciate your contribution. Your code will be helpful other users.

**Comment by bird43** [comment]
Odom is 100% needed for this example. Accept the merge.
