### ISSUE TITLE
ax-12a sudden change in speed of postioncontrol

### ISSUE THREAD

**Issue by JPdeRie** [ROBOTIS-GIT/dynamixel-workbench#170]
Hi Im assuming this is more of a hardware Issue but I hope you could still help me.

Ive made a little robot arm that from left to right and right to left.
Now when I block the movement of the arm. The motors stop and suddenly start operating faster.
Im not quit sure if this is better quality but I do wanna know what the cause of this and how I can control this

Ive made a video of it!
https://www.youtube.com/watch?v=ZxTU52y4Nls&feature=youtu.be

Hope any of you can explain!

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
