### ISSUE TITLE
Check if motor is connected on OpenCR

### ISSUE THREAD

**Issue by mpena2099** [ROBOTIS-GIT/dynamixel-workbench#171]
Hi!

How to check if the dynamixel motor is connected? In OpenCR, it gets stuck on ping (dxl_wb.ping(DXL_ID)) if there is no motor there...

Thanks!
Mauricio

**Comment by routiful** [comment]
Hi :)

You can use `scan()` function
https://github.com/ROBOTIS-GIT/OpenCR/blob/master/arduino/opencr_arduino/opencr/libraries/OpenCR/examples/08.%20DynamixelWorkbench/a_Model_Scan/a_Model_Scan.ino

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
