### ISSUE TITLE
Segmentation fault (core dumped) after fresh install

### ISSUE THREAD

**Issue by Achllle** [ROBOTIS-GIT/dynamixel-workbench#175]
## Settings
1. ROS kinetic
2. Ubuntu 16.04 LTS (Xenial Xerus)
3. Dynamixel model: XM540-W270-R

## Steps to reproduce
I followed the e-manual to install the workbench. I tried both installing from source (checking out `kinetic-devel`) and through debian package. (`catkin_make` when installing from source was successful and I sourced the workspace).

When I do 

```rosrun dynamixel_workbench_single_manager_gui dynamixel_workbench_single_manager_gui```

however I get the following error:

```Segmentation fault (core dumped)```

## Additional info
I can access the motors via the `single_manager.launch` tutorial and can successfully command velocities and positions using the provided launch files

**Comment by routiful** [comment]
Hi :)

You are supposed to open single_manager.launch before launch gui.

http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_workbench/#gui

**Comment by Achllle** [comment]
Ah, did not see that. Thanks for the clarification. Perhaps could the error be replaced with something more sensible, like:

```
[ERROR]: single_manager node needs to be running. 
Did you launch single_manager.launch from dynamixel_workbench_single_manager?
```

**Comment by routiful** [comment]
Thanks! I will add that warning messages next updates :)
