### ISSUE TITLE
Dynamixel-workbench installation error in  Raspberry Pi

### ISSUE THREAD

**Issue by sonary01** [ROBOTIS-GIT/dynamixel-workbench#181]
ISSUE TEMPLATE ver. 0.1.0

Before you open issue, please refer to [ROBOTIS e-Manual](http://emanual.robotis.com/)

1. Which distro of ROS have you installed? (ex, indigo, kinetic, melodic)
Kinetic

2. Which OS have you installed? (ex, Ubuntu 16.04 LTS (Xenial Xerus), Linux Mint 18.x, ...)
Raspbian GNU/Linux 9 (stretch)

3. Which Dynamixel have you used? (ex, MX-28, XM430-W350, ...)

 AX-12A,MX-28, MX-64
4. Write down the commands you used in order

```

git clone https://github.com/ROBOTIS-GIT/dynamixel-workbench.git
git clone https://github.com/ROBOTIS-GIT/dynamixel-workbench-msgs.git
sudo apt-get install ros-kinetic-dynamixel-sdk

```

5. Copy and Paste your error message on terminal

> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package ros-kinetic-dynamixel-sdk
> 

  
6. Please, describe detailedly what difficulty you are in 
Unable to install Dynamixel workbench Dependent packages ros-kinetic-dynamixel-sdk and ros-kinetic-qt-build in Raspberry Pi 3.

**Comment by routiful** [comment]
Hi :)

Did you update and upgrade your raspberry pi ?
Please try below commands and install packages

```
$ sudo apt-get update
$ sudo apt-get upgrade
```

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
