### ISSUE TITLE
How do you install dynamixel-workbench from sources?

### ISSUE THREAD

**Issue by KurtE** [ROBOTIS-GIT/dynamixel-workbench#187]
Sorry, this does not follow your template, but it is more of a generic question.  

Two parts: 

a) How to install the sources with ROS (assuming ROS1).   It may be obvious, but maybe might want to specify in the E-manual: http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_workbench/
That you need to do the git clone of workbench and workbench messages into some place like:
~/catkin_ws/src

And that you then need to use catkin_make

b) How about without ROS? As the library is now also used in OpenCM and OpenCR Arduino sketches, how do you see non ROS apps build using this library?  Probably specifically using the dynamixel_workbench_toolbox code.  At least that looks pretty much like the same code in the Arduino code base. 

Again sorry if this is not the right place to ask this, or if some of this is obvious.

**Comment by gpwhd07** [comment]
This issue will be closed since there were no actions for a while. 
You can reopen this issue to show this issue to the users whenever. Thanks.
