### ISSUE TITLE
Memory issues using Workbench with Hexapod with > 16 same servos

### ISSUE THREAD

**Issue by KurtE** [ROBOTIS-GIT/dynamixel-workbench#189]
Sorry, I am not following the issue template as not sure how to in this case. 

Setup: Assume I have an OpenCM9.04 or an OpenCR board hooked up to my [PhantomX Hexapod](https://www.trossenrobotics.com/phantomx-ax-hexapod.aspx) which has at least 18 servos.  In this case AX-12 servos. 

Now suppose I run a workbench example like: t_find_Dynamixel.   The program will corrupt memory and could give either strange results or fault or...

Some of the issues I have seen so far include: 

a) This example app only allocates space for 16 servos:
```
  uint8_t scanned_id[16] = {0, };
  uint8_t dxl_cnt = 0;
  uint32_t baud[BAUDRATE_NUM] = {9600, 57600, 1000000};
  uint8_t index = 0;
  uint8_t range = 100;

  Serial.print("Size of DynamixelWorkbench: "); Serial.println(sizeof(DynamixelWorkbench), DEC);
  while (index < BAUDRATE_NUM)
  {
    Serial.println(String(baud[index]) + " bps");

    dxl_wb.begin(DEVICE_NAME, baud[index]);
    dxl_wb.scan(&scanned_id[0], &dxl_cnt, range);
```
And so far I don't see that you have any way to specify in your call dxl_wb.scan a way to specify the size of the array you pass in. 

And the function:  bool DynamixelDriver::scan
Will iterate over the range and when it finds all 18 servos, it will keep writing to the array I passed in.  The last two will overwrite whatever that was next in memory.

In addition the scan function will call SetTools(..) which will find that all 18 servos have same nameso it will call addDXL for these 18 servos, on the same Tool object
```
void DynamixelTool::addDXL(const char* model_name, uint8_t id)
{
  strcpy(dxl_info_[dxl_info_cnt_].model_name, model_name);
  setModelNum(model_name);
  dxl_info_[dxl_info_cnt_].id = id;

  dxl_info_cnt_++;
}
```
Which blindly adds the item to the array which again has 16 elements in it.  So again the last two items will overwrite what is next in memory... Probably start of the next tool structure. 

There are probably other issues, with having more than 16 servos, will add on to this issue as I find them.

Thanks
Kurt

**Comment by routiful** [comment]
This issue may solved by PR #190. Thanks!
