### ISSUE TITLE
Error in syncRead Dynamixel

### ISSUE THREAD

**Issue by Leung555** [ROBOTIS-GIT/dynamixel-workbench#201]
ISSUE TEMPLATE ver. 0.1.0

Before you open issue, please refer to [ROBOTIS e-Manual](http://emanual.robotis.com/)

1. Which distro of ROS have you installed? (ex, indigo, kinetic, melodic)
kinetic

2. Which OS have you installed? (ex, Ubuntu 16.04 LTS (Xenial Xerus), Linux Mint 18.x, ...)
Ubuntu 16.04 LTS

3. Which Dynamixel have you used? (ex, MX-28, XM430-W350, ...)
XM430-W350-R
 
4. Write down the commands you used in order
-     - I use the code in this Github
git clone https://github.com/MathiasThor/my_dynamixel_workbench.git
git clone https://github.com/MathiasThor/dynamixel-workbench.git
  ```
$ roslaunch my_dynamixel_workbench_single_manager multi_motor_test.launch
  ```
 
5. Copy and Paste your error message on terminal
By the way This is just an example, It have 18 motors
  ```
SUMMARY
========

PARAMETERS
 * /baud_rate: 4000000
 * /device_name: /dev/ttyUSB0
 * /profile_acceleration: 25000
 * /profile_velocity: 500
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /scan_range: 73

NODES
  /
    position_control (dynamixel_workbench_controllers/position_control)

auto-starting new master
process[master]: started with pid [8799]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 31a41468-eeed-11e8-a38d-9cb6d0e9ef49
process[rosout-1]: started with pid [8812]
started core service [/rosout]
process[position_control-2]: started with pid [8819]
--------------------------------------------------------------------------

  ____                              _          _  
 |  _ \ _   _ _ __   __ _ _ __ ___ (_)_  _____| | 
 | | | | | | | '_ \ / _` | '_ ` _ \| \ \/ / _ \ | 
 | |_| | |_| | | | | (_| | | | | | | |>  <  __/ | 
 |____/ \__, |_| |_|\__,_|_| |_| |_|_/_/\_\___|_| 
  ____  |___/ ____    ____       _                
 |  _ \ / _ \/ ___|  |  _ \ _ __(_)_   _____ _ __ 
 | |_) | | | \___ \  | | | | '__| \ \ / / _ \ '__|
 |  _ <| |_| |___) | | |_| | |  | |\ V /  __/ |   
 |_| \_\\___/|____/  |____/|_|  |_| \_/ \___|_|   
                                                  
--------------------------------------------------------------------------

MODEL   : XM430-W350
ID      : 11

MODEL   : XM430-W350
ID      : 12

MODEL   : XM430-W350
ID      : 13

MODEL   : XM430-W350
ID      : 31

MODEL   : XM430-W350
ID      : 32

MODEL   : XM430-W350
ID      : 33

MODEL   : XM430-W350
ID      : 51

MODEL   : XM430-W350
ID      : 52

MODEL   : XM430-W350
ID      : 53

MODEL   : XM430-W350
ID      : 61

MODEL   : XM430-W350
ID      : 62

MODEL   : XM430-W350
ID      : 63

MODEL   : XM430-W350
ID      : 71

MODEL   : XM430-W350
ID      : 72

MODEL   : XM430-W350
ID      : 73
--------------------------------------------------------------------------------------------------------------------------------
Error in syncRead
Error in syncRead
Error in syncRead
Error in syncRead
Error in syncRead
Error in syncRead

  ```
  
6. Please, describe detailedly what difficulty you are in 

    - I use the position controller to control 18 motors with some modification of the code to received the data from the motor and it seems work, until I have use the R+ manager to tune the parameter of my motor and also update the firmware from v.41 to v.42 , 

   - then when I'm back to run the position controller again. It shown that I can find all of the motor but It show "Error in syncRead" I have checked the wiring hardware of each motor no problem. but If I try to connect the motor more than 15 motor when I run the position control I start to get this error no matter I use which combination of the motor.

**Comment by routiful** [comment]
Last issue might be help you #198

**Comment by gpwhd07** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
