### ISSUE TITLE
DynamixelWorkbench API Problem

### ISSUE THREAD

**Issue by fatihirim** [ROBOTIS-GIT/dynamixel-workbench#202]
Hello

I am using ROS Kinetic, on Ubuntu 16.04 LTS. Trying to run OpenManipulator on QT.

I have cloned the repositories as described in Section 4 of 

[http://emanual.robotis.com/docs/en/platform/openmanipulator/?fbclid=IwAR3hL4ytKue9PMes2mvsbJLmCcYT6v-uCycYCQu9rEGqj3jKTSeV6l_rWZs#embedded-board-setup].

When I try to compile OpenManipulator I get following error:

/home/fatih/WORKSPACES/ws_open_manipulator/src/open_manipulator/open_manipulator_libs/src/Dynamixel.cpp:70: error: ‘class DynamixelWorkbench’ has no member named ‘torqueOn’
     result = dynamixel_workbench_->torqueOn(dynamixel_.id.at(index), &log);
                                    ^

Seems like the dynamixel_workbench_toolbox does not provide the required API for OpenManipulator. When I check DynamixelWorkbench class, indeed it does not contain the torqueOn method signature at all.

Can you please check?

Thanks

**Comment by routiful** [comment]
Hi

You are supposed to download toolbox in develop branch.
It will be merged to master branch soon.

**Comment by fatihirim** [comment]
Hello

This does not help. Even if I download toolbox (or the entire workbench) from develop branch then other inconsistencies occur (missing class members)

For ex: When I download only toolbox from develop branch I have:

/home/fatih/WORKSPACES/ws_open_manipulator/src/dynamixel-workbench-master/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp:319: error: call of overloaded ‘writeRegister(uint8_t&, const char [10], int)’ is ambiguous
         comm_result = dynamixel_driver_->writeRegister(dxl_id_, "Baud_Rate", 4);
                                                                               ^

When I download the entire workbench from develop branch, I get:

/home/fatih/WORKSPACES/ws_open_manipulator/src/dynamixel-workbench-develop/dynamixel_workbench_controllers/src/dynamixel_workbench_controllers.cpp:283: error: ‘dynamixel_workbench_msgs::DynamixelState {aka struct dynamixel_workbench_msgs::DynamixelState_<std::allocator<void> >}’ has no member named ‘name’
     dynamixel_state[id_cnt].name = dxl.first;
                             ^

Could you tell exactly which package to download from which branch in order to get everything compiled correctly? 

Thanks

**Comment by fatihirim** [comment]
Hi

Thanks, now it seems to build correctly.
When do you expect to finalize the fixes and merge all development work into master?
Could you please notify when this is done?

Thanks in advance.

**Comment by routiful** [comment]
I updated new version, please check it :)

**Comment by gpwhd07** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
