### ISSUE TITLE
Catkin_make hangs at 88% on install on RPI3, linux mate

### ISSUE THREAD

**Issue by Chick92** [ROBOTIS-GIT/dynamixel-workbench#211]
Hi, 

Installation of the new dynamixel workbench ecosystem hangs on 88% -

 [ 88%] Building CXX object dynamixel-workbench/dynamixel_workbench_single_manager_gui/CMakeFiles/dynamixel_workbench_single_manager_gui.dir/src/main.cpp.o

This seems to be localised to RPI3 running linux mate, as the installation process described in the emanual works on x86 architecture. 

Also, are the installation instructions for the previous tutorials backed up anywhere, i'd done a lot of work on the previous iteration and your new iteration is not backwards compatible.

Thanks, Ben

**Comment by routiful** [comment]
You have to install qt library before you make single_manager_gui. But I recommend don't use that package in RPI3.

I attached link to manual for last version 
https://github.com/ROBOTIS-GIT/emanual/blob/87ce5ee70df8d43c7b32edb6e3f59f8388b97cfa/docs/en/software/dynamixel/dynamixel_workbench.md

**Comment by gpwhd07** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
