### ISSUE TITLE
How to properly follow a generated trajectory with moveit

### ISSUE THREAD

**Issue by jcgarciaca** [ROBOTIS-GIT/dynamixel-workbench#232]
It is not an issue but a doubt.
I am planning and executing a trajectory with moveit. However the motors move so fast such that they actually don't follow the trajectory. If I change the `write_period` value, then motors follow the trajectory but show a "stepped movement". Then:

1. Is it required to keep a ratio between `sample_duration` and `write_period`?
2. Is it possible to smooth the trajectory for instance with changing filter values?

**Comment by routiful** [comment]
@jcgarciaca 
Sorry for late reply.
`sample_duration` means that trajectory -generated by moveit- sampling time. It may higher you can subscribe many points on trajectory.
'write_period' means that time period of Dynamixel packet transmission.
