### ISSUE TITLE
Using XH540-V270 with the dynamixel workbench

### ISSUE THREAD

**Issue by philko4711** [ROBOTIS-GIT/dynamixel-workbench#237]
Dear Ladies and Gentlemen,
we want to use a XH540-V270 dynamixel on our robot arm. Unfortunately, it is currently not supported, are you planning on supporting this device in the future?
Thank you very much.

**Comment by yhna** [comment]
Hello, @philko4711 
Unfortunately, we do not plan to support this model.
To use this model, you have to program with dynamixel sdk.
See this [link](http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_sdk/overview/) for a manual on dynamixel sdk.
Thanks.

**Comment by RyanJaehyunShim** [comment]
@philko4711 

We added XH540 models. Let us know you encounter any problems while using our package

Regards,
Ryan
