### ISSUE TITLE
Failed to read Dynamixel MX-106 after failing firmware update

### ISSUE THREAD

**Issue by giovannacoelho** [ROBOTIS-GIT/dynamixel-workbench#251]
I'm working with MX-106 servos, protocol 2.0, and after using R+ Manager and the firmware update failed, the servos can't be read anymore. I tried recovery on Dynamixel Wizard 2.0 too but I also fails. I'd like to know if there is a way to install an earlier version of this servos firmware, the one that failed was version 43. There is no update for R+ Manager, and the latest update didn't solve this.
![image](https://user-images.githubusercontent.com/51714183/59287560-42eef000-8c48-11e9-8aad-caa2e7d002de.png)

**Comment by RyanJaehyunShim** [comment]
@giovannacoelho 

Please ask your question at the link below
(http://en.robotis.com/service/forum.php)

Regards,
Ryan
