### ISSUE TITLE
dynamixel-workbench good start but limited to single type of servo 

### ISSUE THREAD

**Issue by mwalkeriii** [ROBOTIS-GIT/dynamixel-workbench#255]
ISSUE TEMPLATE ver. 1.0.0

Before you open issue, please refer to [ROBOTIS e-Manual](http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_workbench/)

1. How to setup? (ex, U2D2, OpenCR,...) Most simple setup is OpenCM9.04 + Expansion. Connect two different types of Dynamixel to the board. My setup is one XL320 and on XL430, both connected to the CM. The CM is power by 7.4v powering the XL320 and the XL430 is power via 11.2

2. Which Dynamixel have you used? and how many? **(Please describe below format to all connected Dynamixels)**

   - Model Name
XL320, XL430
   - ID
1, 2
   - Baud Rate of Dynamixels
1M
   - Protocol Version
 2.0
3. Write down the commands you used in order

roslaunch dynamixel_workbench_controllers mylaunch_controllers.launch

#this command finds all the correct servos, and attempts to publish their state to /dynamixel_workbench/dynamixel_state ros topic
 
4. Copy and Paste your error message on terminal

  There is no error message in this iteration, however the information for the second servo type is incorrect.
  
5. Please, describe detailedly what difficulty you are in 

    Using dynamixel_workbench_controllers
Only one type of servo will work at a time. One type meaning one type that shares the same registers addresses for the requested data. I'm assuming because only one sync_read command is used to read one set of Dynamixel registers. When the XL320 is first, the sync_read tries to read the XL320 registers for the XL430 and vice versa. I suspect that ultimately some form of either multiple sync_reads for different sets "tools" of servos (ie read all the Present_velocities from all the XL320 servos, then read all the Present_velocities from the XL430 servos), or something like a Bulk_write (except there seems to be a limit to the number of Dynamixel IDs a group read/write can address. 

Is there any way around this without rewriting the code to use two separate calls to sync_read based on the different "groups" ie "tools_cnt" of Dynamixel detected?

It seems as if some of the code it written to distinguish the separate "tools_cnt" but then it does not use that information to read the correct registers for each set of Dynamixels specifically in "DynamixelController::readCallback". Am I understanding this correctly?

If so, any recommendations?

**Comment by RyanJaehyunShim** [comment]
@mwalkeriii 

Our system currently does not support such situations. Please use the same type of motors (or motors with the same control table). 

Regards,
Ryan
