### ISSUE TITLE
RH-P12-RN, RH-P12-RN(A) miss some control items

### ISSUE THREAD

**Issue by garaemon** [ROBOTIS-GIT/dynamixel-workbench#256]
https://github.com/ROBOTIS-GIT/dynamixel-workbench/pull/253 adds the control tables for RH-P12-RN and RH-P12-RN(A). However, it lacks some control items such as "Hardware Error Status" which are listed in the [e-manual](http://support.robotis.com/en/product/actuator/dynamixel_pro/dynamixelpro/rh-p12-rn.htm).

Could you add the missing control items?

**Comment by RyanJaehyunShim** [comment]
@garaemon 

I updated the control table in the devel.branch. It will be merged to the master branch this Friday. If you need it before that time, please download it from the devel branch. 

Regards,
Ryan
