### ISSUE TITLE
How to set up velocity and acceleration profile for dynamixel motors

### ISSUE THREAD

**Issue by madlink306** [ROBOTIS-GIT/dynamixel-workbench#266]
I don't know where to post this. So maybe here. Sorry if it's not the right place, and please point me to where I can ask this kind of question.

So, anyway, I'm trying to learn to control dynamixel motr. And I know we can use velocity and acceleration profile to create trapezoidal profile. The infomation I get from the manual website of dynamixel. http://emanual.robotis.com/docs/en/dxl/x/xm430-w350/#specifications

1. Which value should I set for velocity profile? For example I read in the datasheet that at 12V the velocity is 30 rev/min. As I understand that I should set the value of velocity profile to 132 (30 divided to 0.229 rev/min = 132). Is that correct?

2. What about the acceleration profile? I see nothing mention in the datasheet so I don't know what is the max acceleration for the motor. The datasheet say that, acceleration profile value will not exceed 50% of velocity. Does that mean I should set the acceleration value to 61 (50% of 132)?

3. Time calculation for trapezoidal profile is t1 = 64 * (Velocity profile/Acceleration profile), t2 = 64 * delta_position / Velocity profile. What is the units and values using in here? Is that the real velocity value (30 rev/min) or the integer value set before(132). If so, wouldn't t1 value would be in minute? same with acceleration? What about delta_position is that in integer value or rev value?

Thank you for your help.

**Comment by rjshim** [comment]
@madlink306 

Please ask your question at [the link](http://en.robotis.com/model/board.php?bo_table=robotis_faq_en)
Ryan
