### ISSUE TITLE
ModelInfo not loaded from Control Table (uses static values instead)

### ISSUE THREAD

**Issue by khoshrav** [ROBOTIS-GIT/dynamixel-workbench#269]
ISSUE TEMPLATE ver. 1.0.0

1. How to setup? (ex, U2D2, OpenCR,...)
Using MX-28 (2.0) with Usb2dynamixel.

2. Which Dynamixel have you used? and how many? **(Please describe below format to all connected Dynamixels)**

   - Model Name MX-28 (2.0)

   - ID: 1, 2, 3

   - Baud Rate of Dynamixels: 1000000

   - Protocol Version: 2.0
 
4. Please, describe detailedly what difficulty you are in 

    - I have overwritten the default values in the control table using the R+ Manager (specifically for the Homing Offset, the Min Position and the Max Position).
When an instance of the Dynamixel Tool is initialized, the getModelInfo(model_number) function loads static values that are hardcoded in. It does not reflect the actual values for the model info in the motor's control table.

**Comment by rjshim** [comment]
@khoshrav  

Any parameters on the control table of EEPROM area (including homing offset) cannot be changed while torque is on. If you have more questions about Dynamixel, leave them at the [link](http://en.robotis.com/model/board.php?bo_table=robotis_faq_en).

Regards,
Ryan
