### ISSUE TITLE
XH430-W350 daisy chain 

### ISSUE THREAD

**Issue by sarahToonsi** [ROBOTIS-GIT/dynamixel-workbench#276]
I am connecting two XH430-W350 motors in daisy chain and using U2D2 as an interface. When Running  rosrun dynamixel_workbench_controllers find_dynamixel /tty/USB0 I can only see one of the them and its ID, how can I access the second one and give it an ID

**Comment by rjshim** [comment]
@sarahToonsi 

You will need to use [Dynamixel Wizard](http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_wizard2/) and set motor ids first. 
Ryan
