### ISSUE TITLE
[workbench] switch PRO+ to current control mode

### ISSUE THREAD

**Issue by yoshito-okada** [ROBOTIS-GIT/dynamixel-workbench#284]
DynamixelWorkbench does not allow PRO+ to switch to current control mode despite PRO+ actually supports it and the Dinamixel Wizard 2.0 does allow.  The if statement below would be fixed.
https://github.com/ROBOTIS-GIT/dynamixel-workbench/blob/0246b7fe3d789d9356763cd9930676af55decc95/dynamixel_workbench_toolbox/src/dynamixel_workbench_toolbox/dynamixel_workbench.cpp#L696-L700

**Comment by ROBOTIS-Will** [comment]
@yoshito-okada 
Thank you for reporting the issue! :)
