### ISSUE TITLE
I have problem when trying to run 4 dynamixel...

### ISSUE THREAD

**Issue by dongheup** [ROBOTIS-GIT/dynamixel-workbench#29]
is my terminal show up....

kist@kist:~/catkin_ws$ roslaunch my_dynamixel_workbench_tutorial dynamixel_controllers_potenit.launch 
... logging to /home/kist/.ros/log/90d7ac3a-f988-11e6-8198-a0c5894b1d10/roslaunch-kist-29902.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://kist:44135/

PARAMETERS
 * /dynamixel_workbench_potision_ear_arm_controller/baud_rate: 57600
 * /dynamixel_workbench_potision_ear_arm_controller/device_name: /dev/ttyUSB0
 * /dynamixel_workbench_potision_ear_arm_controller/left_arm_motor/motor_id: 4
 * /dynamixel_workbench_potision_ear_arm_controller/left_ear_motor/motor_id: 2
 * /dynamixel_workbench_potision_ear_arm_controller/motor_model: XM430_W210_R
 * /dynamixel_workbench_potision_ear_arm_controller/profile_acceleration: 10
 * /dynamixel_workbench_potision_ear_arm_controller/profile_velocity: 100
 * /dynamixel_workbench_potision_ear_arm_controller/protocol_version: 2.0
 * /dynamixel_workbench_potision_ear_arm_controller/right_arm_motor/motor_id: 3
 * /dynamixel_workbench_potision_ear_arm_controller/right_ear_motor/motor_id: 1
 * /rosdistro: indigo
 * /rosversion: 1.11.20

NODES
  /
    dynamixel_workbench_potision_ear_arm_controller (dynamixel_workbench_controllers/dynamixel_workbench_position_ear_arm_control)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[dynamixel_workbench_potision_ear_arm_controller-1]: started with pid [29920]
[ INFO] [1487837933.814076954]: dynamixel_workbench_position_eararm_control : Init OK!
[ INFO] [1487837933.817125381]: Succeeded to open the port(/dev/ttyUSB0)!
[ INFO] [1487837933.817835424]: Succeeded to change the baudrate(57600)
!
[ INFO] [1487837933.818378638]: right_ear_motor_id: 1
[ INFO] [1487837933.818398075]: right_ear_motor_model: XM430_W210_R
[ INFO] [1487837933.818420798]: right_ear_motor_protocol_version_: 2.0

[ INFO] [1487837933.859098936]: left_ear_motor_id: 2
[ INFO] [1487837933.859126318]: left_ear_motor_model: XM430_W210_R
[ INFO] [1487837933.859144538]: left_ear_motor_protocol_version_: 2.0
[ INFO] [1487837933.860113283]: right_arm_motor_id: 3
[ INFO] [1487837933.860149768]: right_arm_motor_model: XM430_W210_R
[ INFO] [1487837933.860175281]: right_arm_motor_protocol_version_: 2.0
[ INFO] [1487837933.861029285]: left_arm_motor_id: 4
[ INFO] [1487837933.861052580]: left_arm_motor_model: XM430_W210_R
[ INFO] [1487837933.861077238]: left_arm_motor_protocol_version_: 2.0

REQUIRED process [dynamixel_workbench_potision_ear_arm_controller-1] has died!
process has died [pid 29920, exit code -11, cmd /home/kist/catkin_ws/devel/lib/dynamixel_workbench_controllers/dynamixel_workbench_position_ear_arm_control __name:=dynamixel_workbench_potision_ear_arm_controller __log:=/home/kist/.ros/log/90d7ac3a-f988-11e6-8198-a0c5894b1d10/dynamixel_workbench_potision_ear_arm_controller-1.log].
log file: /home/kist/.ros/log/90d7ac3a-f988-11e6-8198-a0c5894b1d10/dynamixel_workbench_potision_ear_arm_controller-1*.log
Initiating shutdown!

[dynamixel_workbench_potision_ear_arm_controller-1] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

how can I solve this problem....?

**Comment by routiful** [comment]
Hi,
dynamixel_workbench_controllers package shows an example how to run Dynamixel in ROS.
Controllers package includes four nodes and these nodes have same sequences.

1. get some parameters on launch file
2. init motors you need
3. torque on
4. control Dynamixel on control loop

But every functions to control Dynamixel in the nodes is developed for only two Dynamixels. 
Therefore, you need to change some code for controlling four Dynamixels.

dynamixel_workbench depends on [DynamixelSDK](https://github.com/ROBOTIS-GIT/DynamixelSDK). 
I think you receive some information while you change a code in dynamixel-workbench in[ DynamixelSDK wiki ](https://github.com/ROBOTIS-GIT/DynamixelSDK/wiki)

Thanks.
