### ISSUE TITLE
Change request for dynamixel_workbench_single_manager

### ISSUE THREAD

**Issue by hvdbrand** [ROBOTIS-GIT/dynamixel-workbench#30]
This is a small change request for the dynamixel_workbench_single_manager.
Currently, the program scans for all ids and connects to the dynamixel with the highest id that can be found using protocol 2.0. If no protocol 2.0 dynamixel motors are found, a connection is made to motor with highest id which communicates via protocol 1.0.
This option is useful for discovery of motors.

However, in some cases multiple dynamixel motors are connected to the same bus and you want to address a specific motor. At the moment this is not possible. Therefore, it is suggested to add an extra argument to the program: motor_id. If it is unset or set to zero, the application should just scan ids as is the case now.
However, if the id is set to a positive value the application should only try to connect to the dynamixel with that specific id. This would ease changing the configuration of multiple dynamixels on the same bus.

**Comment by routiful** [comment]
Hi, hvdbrand

Thank you for your friendly feedback. I will consider applying it to the next release.

Thanks.
