### ISSUE TITLE
ROS Noetic Compatibility 

### ISSUE THREAD

**Issue by swinterbotix** [ROBOTIS-GIT/dynamixel-workbench#308]
If compiled from source, would there be any foreseeable issues getting the dynamixel_workbench_toolbox ROS package working on ROS Noetic?

**Comment by tiexuedanxin** [comment]
> If compiled from source, would there be any foreseeable issues getting the dynamixel_workbench_toolbox ROS package working on ROS Noetic?
hello, have you try it, is everything ok?

**Comment by swinterbotix** [comment]
Nope, haven't tried it out yet.

**Comment by swinterbotix** [comment]
Hi @tiexuedanxin,

I've tried using the package in ROS Noetic and have had no issues.
