### ISSUE TITLE
Dynamixel workbench velocity controller with wheel tutorial not working

### ISSUE THREAD

**Issue by mlin2** [ROBOTIS-GIT/dynamixel-workbench#31]
Hi there,

your tutorial at http://wiki.ros.org/dynamixel_workbench_controllers/Tutorials/VelocityControl doesn't work without modifications to the launch file. In your code for the velocity controller https://github.com/ROBOTIS-GIT/dynamixel-workbench/blob/master/dynamixel_workbench_controllers/src/dynamixel_workbench_velocity_control.cpp you're using the following format for configuration options: e.g. "motor_id_" while in the tutorial's launch file you're using the key without the underscores, e.g. "motor_id". That's why the launch file won't work as it is described in your tutorial.

Please change the parsing part of your code to match the format of properties in the launch file of the tutorial.

Kind regards

**Comment by routiful** [comment]
Hi :)

Wiki explains about latest version of dynamixel-workbench. 
You may find it in develop branch. We will update it on master branch soon.
Sorry for your inconvenience.

Thanks.
