### ISSUE TITLE
convertValue2Radian Assumptions

### ISSUE THREAD

**Issue by mrunaljsarvaiya** [ROBOTIS-GIT/dynamixel-workbench#315]
Seems like the function `convertValue2Radian` assumes the "Present_Position" data received from the dynamixel lies between `value_of_min_radian_position` (0 for XM 540-270) and `value_of_max_radian_position` (4096) or alternatively between - PI and PI. However, referring to https://emanual.robotis.com/docs/en/dxl/x/xm540-w270/#present-position132, if not in Position Control Mode, the data can lie between -2,147,483,648 to 2,147,483,647. Is this a bug or is this only supposed to be using under the previous assumption?

**Comment by ROBOTIS-Will** [comment]
Hi @mrunaljsarvaiya 
I'm sorry about the delayed response on your issue.
DYNAMIXEL can count the encoder value up wiithin 4 byte signed integer range(which is -2,147,483,648 .. 2,147,483,647), but as you correctly identified, the conversion method only supports within a single rotation(0 .. 4095) which is mapped into -PI to PI.
Please note that when DYNAMIXEL does not save the turn count after certain conditions such as power cycle or changing the operating mode.
Thank you.

**Comment by ROBOTIS-Will** [comment]
Closing this issue as there isn't recent activity. Please feel free to reopen when necessary.
