### ISSUE TITLE
How to control dynamixels with Moveit

### ISSUE THREAD

**Issue by Florian9638** [ROBOTIS-GIT/dynamixel-workbench#323]
Hi,
I have two XC430-W150 and I would like to move them via Moveit! (ROS Melodic).
I followed the dynamixel workbench emanual and everything works, but there are no info regarding moveit, I would really appreciate it if you could provide me some guidelines.

What I did until now is the following:

I launch the following command:
$ roslaunch dynamixel_workbench_controllers dynamixel_controllers.launch

And inside dynamixel_controllers.launch i set use_moveit to true:
<arg name="use_moveit"              default="true"/>

(this means my dynamixel actuators are now ready to take commands from moveit, rigth?)

Then I created my 2 degree of freedom robot urdf and used the moveit setup assistant to create a robot_moveit_config folder.

I guess the next step is to create some yaml files to specify the controller and the joints. Do you have a list of those or some examples? It would be really helpful.

Thank you in advance

**Comment by ROBOTIS-Will** [comment]
Hi @Florian9638 
You can refer to the Moveit documentation for setting up your robot.
https://ros-planning.github.io/moveit_tutorials/doc/controller_configuration/controller_configuration_tutorial.html
However, please note that Moveit is an ideal solution for industrial robots, not for low DOF robot with less than 6 DOF.
You might need to write your own custom controller in the end.
Thank you.

**Comment by ROBOTIS-Will** [comment]
Closing this issue as there isn't recent activity. Please feel free to reopen when necessary.
