### ISSUE TITLE
Current reading looks weird

### ISSUE THREAD

**Issue by lara-z** [ROBOTIS-GIT/dynamixel-workbench#332]
ISSUE TEMPLATE ver. 1.0.0

Before you open issue, please refer to [ROBOTIS e-Manual](http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_workbench/)

1. How to setup? U2D2

2. Which Dynamixel have you used? and how many? **(Please describe below format to all connected Dynamixels)**

   - Model Name XM430-W210-T

   - ID 5

   - Baud Rate of Dynamixels 1000000

   - Protocol Version 2.0
 
3. Write down the commands you used in order
Sorry, I can't seem to transfer the indentions, but I put line breaks at the end of the if statements so hopefully you get the idea
   ` DXL_ID = 5`
`ADDR_PRO_GOAL_CURRENT       = 38`
`ADDR_PRO_PRESENT_CURRENT    = 126`

   `# Read present current`
    `dxl_present_current, dxl_comm_result, dxl_error = packetHandler.read4ByteTxRx(portHandler, DXL_ID, ADDR_PRO_PRESENT_CURRENT)`
   ` if dxl_comm_result != COMM_SUCCESS:`
        `      print("%s" % packetHandler.getTxRxResult(dxl_comm_result))`
   ` elif dxl_error != 0:`
        `print("%s" % packetHandler.getRxPacketError(dxl_error))`

    `# Read goal current`
   ` dxl_goal_current, dxl_comm_result, dxl_error = packetHandler.read4ByteTxRx(portHandler, DXL_ID, ADDR_PRO_GOAL_CURRENT)`
    `if dxl_comm_result != COMM_SUCCESS:`
       ` print("%s" % packetHandler.getTxRxResult(dxl_comm_result))`
    `elif dxl_error != 0:`
       ` print("%s" % packetHandler.getRxPacketError(dxl_error))`

   ` print("[ID:%03d] PresCurrent:%03d, GoalCurrent:%03d" % (DXL_ID, dxl_present_current, dxl_goal_current))`
 
4. Copy and Paste your error message on terminal

 no error
  
5. Please, describe detailedly what difficulty you are in 
The goal current and present current readings seem exorbitantly high (see image below). Based on the control table (https://emanual.robotis.com/docs/en/dxl/x/xm430-w210/#control-table), they should be in mA, and I expect that the value is on the order of ~1A. The numbers I'm getting seem way too high to be in mA. What is the unit of the present and goal current reading, or what am I doing wrong?
![image](https://user-images.githubusercontent.com/46114442/118690776-6298d680-b7d6-11eb-9d2f-8920cc3f5eb9.png)

**Comment by ROBOTIS-Will** [comment]
Hi @lara-z 
The Goal Current and Present Current use 2 byte data.
Since you are trying to read 4byte data with `read4ByteTxRx` method, the read value will be incorrect.
In addition, current value can be negative so don't forget to apply `2's complement` to the received value.

**Comment by ROBOTIS-Will** [comment]
Closing this issue as there isn't recent activity. Please feel free to reopen when necessary.
