### ISSUE TITLE
How do you check hardware errors in the control table?

### ISSUE THREAD

**Issue by lara-z** [ROBOTIS-GIT/dynamixel-workbench#333]
ISSUE TEMPLATE ver. 1.0.0

Before you open issue, please refer to [ROBOTIS e-Manual](http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_workbench/)

1. How to setup? (ex, U2D2, OpenCR,...)
U2D2

2. Which Dynamixel have you used? and how many? **(Please describe below format to all connected Dynamixels)**

   - Model Name: XM430-W210-T

   - ID: 1

   - Baud Rate of Dynamixels: 1000000

   - Protocol Version: 2.0
 
3. Write down the commands you used in order

  ```
ADDR_PRO_PRESENT_CURRENT    = 126
ADDR_PRO_HARDWARE_ERROR     = 70

dxl_present_current, dxl_comm_result, dxl_error = packetHandler.read2ByteTxRx(portHandler, motor_id, ADDR_PRO_PRESENT_CURRENT)
        if dxl_comm_result != COMM_SUCCESS:
            print("%s" % packetHandler.getTxRxResult(dxl_comm_result))
        elif dxl_error != 0:
            print("[ID:%-2d]: %s" % (motor_id, packetHandler.getRxPacketError(dxl_error)))
            dxl_error_message, dxl_comm_result, dxl_error = packetHandler.read1ByteTxRx(portHandler, motor_id, ADDR_PRO_HARDWARE_ERROR)
            print(dxl_error_message)
            print(dxl_comm_result)
            print(dxl_error)
  ```
 
4. Copy and Paste your error message on terminal

  ```
 [ID:1 ]: [RxPacketError] Hardware error occurred. Check the error at Control Table (Hardware Error Status)!
1
0
128
  ```
  
5. Please, describe detailedly what difficulty you are in 

What syntax do I use to access the hardware error details in the Control Table? When I try to access the hardware error status through the control table (address 70) and print the messages from it, I get an error message with a value of 1, a comm result with a value of 0, and an error with a value of 128. I am unsure how to read this. I see from the manual (https://emanual.robotis.com/docs/en/dxl/x/xm430-w210/#hardware-error-status70) that the values of different bits will reveal my motor error, but I am unsure what syntax/code to write to access this and couldn't find any python examples online.

Since I am running the python file I use to command the dynamixel motors through the command line (as opposed to using R+ Task 2.0 or some of the provided software), I need to disconnect from the command line in order to connect to the R+ Manager. After disconnecting from the command line and connecting in the R+ Manager, when I check address 70, I always see a 0, which I assume means no error. Please help!

**Comment by ROBOTIS-Will** [comment]
hi @lara-z 
I'm sorry about the delayed response.
The Hardware Error Status is a 1 byte data so please try reading it with `read1ByteTxRx` instead of `read2ByteTxRx`.
Please see if this resolves your issue.
Thanks!

**Comment by ROBOTIS-Will** [comment]
Closing this issue as there isn't recent activity. Please feel free to reopen when necessary.
