### ISSUE TITLE
Unreasonable current readings

### ISSUE THREAD

**Issue by lara-z** [ROBOTIS-GIT/dynamixel-workbench#334]
ISSUE TEMPLATE ver. 1.0.0

Before you open issue, please refer to [ROBOTIS e-Manual](http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_workbench/)

1. How to setup? (ex, U2D2, OpenCR,...)
U2D2

2. Which Dynamixel have you used? and how many? **(Please describe below format to all connected Dynamixels)**

   -  Model Name: XM430-W210-T

    - ID: 1

    - Baud Rate of Dynamixels: 1000000

    - Protocol Version: 2.0
 
3. Write down the commands you used in order
  
```
portHandler = PortHandler('COM3')
DXL_ID = 1
ADDR_PRO_PRESENT_CURRENT = 126

def curr2Amps(current_reading): 
   # converts current reading to units of Amps
    return current_reading*2.69/1000

dxl_goal_current, dxl_comm_result, dxl_error = packetHandler.read2ByteTxRx(portHandler, DXL_ID, ADDR_PRO_GOAL_CURRENT)
if dxl_comm_result != COMM_SUCCESS:
        print("%s" % packetHandler.getTxRxResult(dxl_comm_result))
elif dxl_error != 0:
        print("[ID:%-2d]: %s" % (DXL_ID, packetHandler.getRxPacketError(dxl_error)))
        dxl_error_message, dxl_comm_result, dxl_error = packetHandler.read1ByteTxRx(portHandler, DXL_ID, ADDR_PRO_HARDWARE_ERROR)

dxl_present_current, dxl_comm_result, dxl_error = packetHandler.read2ByteTxRx(portHandler, DXL_ID, ADDR_PRO_PRESENT_CURRENT)
if dxl_comm_result != COMM_SUCCESS:
        print("%s" % packetHandler.getTxRxResult(dxl_comm_result))
elif dxl_error != 0:
        print("[ID:%-2d]: %s" % (DXL_ID, packetHandler.getRxPacketError(dxl_error)))

print("Raw Current: %8.2f, Current (Amps): %3.3fA, Raw Goal Current: %8.2f, Goal Current (Amps): %3.3fA" % (dxl_present_current, curr2Amps(dxl_present_current),dxl_goal_current, curr2Amps(dxl_goal_current)))

  ```
 
4. Copy and Paste your error message on terminal

no error message
  
5. Please, describe detailedly what difficulty you are in 
![image](https://user-images.githubusercontent.com/46114442/121588954-841b6580-ca04-11eb-8760-f6663db2f5ff.png)

I am currently using current-based position control, but this was an issue even when using extended position control. The current readings have unreasonably high values (see screenshot) even when there is load on the motors, regardless of whether I measure current during motor motion or after the motor finishes motion (and is resting supporting a load with torque enabled). How can I fix this?

**Comment by ROBOTIS-Will** [comment]
hi @lara-z 
The Present Current can be a negative value with a 2's complement representation, therefore, the value should be converted to signed format.
Thank you.

**Comment by ROBOTIS-Will** [comment]
Closing this issue as there isn't recent activity. Please feel free to reopen when necessary.
