### ISSUE TITLE
ROS Noetic - Current-based Position Control Mode - position and torque control

### ISSUE THREAD

**Issue by kaltenegger** [ROBOTIS-GIT/dynamixel-workbench#340]
**1. Setup:**

U2D2

**2. Dynamixel Servo:**

   - MX-106T (2.0) (1 piece)
   - ID 1
   - Baud Rate of Dynamixels 57600bps
   - Protocol Version 2.0
 
**3. Starting the servo with:**

```
roslaunch dynamixel_workbench_controllers dynamixel_controllers.launch
```
 
**4. Error Message:**

No error message
  
**5. Problem description:**

I try to use the Dynamixel MX-106T (2.0) in Operating Mode 5 (Current-based Position Control Mode) with ROS Noetic on Ubuntu 20.04. Thus I am using the the dynamixel_skd on `master` master, dynamixel-workbench on `noetic-devel` branch, and the dynamixel_workbench_msgs on `master` branch. To move the servo [trajectory_msgs/JointTrajectory](http://docs.ros.org/en/api/trajectory_msgs/html/msg/JointTrajectory.html) are published from my ROS node (written in Python). The servo is moving to the defined position, but setting the effort in the [trajectory_msgs/JointTrajectroyPoint](http://docs.ros.org/en/api/trajectory_msgs/html/msg/JointTrajectoryPoint.html) has no influnce. The servo is always using the maximum effort.

Is there a way to control position and torque (controlled via current) with ROS Noetic?

**Comment by ROBOTIS-Will** [comment]
Hi @kaltenegger 

Thank you for your inquiry, but I'm afraid that the `dynamixel_workbench_controllers` package doesn't have an implementation for the effort at the moment.
You may try to implement your own effort controller, but DYNAMIXEL doesn't have a conversion constant value between torque and current (which DYNAMIXEL reads).
Thank you.

**Comment by kaltenegger** [comment]
Thank you for the quick response.

Just for clarification: there is no way to control position and current at the same time with ROS Noetic at the moment. This would mean that Operating Mode 5 (Current-based Position Control Mode) is not compatible with ROS Noetic at this point.

**Comment by ROBOTIS-Will** [comment]
@kaltenegger 
Thank you for sharing your insight in regard with this and sorry about your inconvenience.
I believe the [dynamixel_control](https://github.com/youtalk/dynamixel_control) package will cover this effort control, but it is currently being written for ROS2.

**Comment by kaltenegger** [comment]
Thank you for the information.

So Operating Mode 5 (Current-based Position Control Mode) is not supported for ROS Noetic, thus the ticket can be closed.

**Comment by suho0515** [comment]
well... I'm using dynamixel with mode 5 with dynamixel service request in ros1 noetic. so, I belive you could use operating mode 5.
