### ISSUE TITLE
Support for ros2-galactic: colcon build error

### ISSUE THREAD

**Issue by 3mrrrx** [ROBOTIS-GIT/dynamixel-workbench#347]
basic complication unsing colcon on ros2-galactic results in errors on both branches:

 - ros2-devel
 - ros2 

Cmds:
`
source /opt/ros/galactic/setup.bash
rosdep install --from-paths src --ignore-src -r -y
colcon build --symlink-install --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
`

error:
`
fatal error: hardware_interface/base_interface.hpp: No such file or directory
   20 | #include <hardware_interface/base_interface.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`

**Comment by 3mrrrx** [comment]
these  the available libraries in for both galatic and foxy.


 `
ros-galactic-dynamic-edt-3d                          ros-galactic-dynamixel-sdk-custom-interfaces-dbgsym
ros-galactic-dynamic-edt-3d-dbgsym                   ros-galactic-dynamixel-sdk-dbgsym
ros-galactic-dynamixel-sdk                           ros-galactic-dynamixel-sdk-examples
ros-galactic-dynamixel-sdk-custom-interfaces         ros-galactic-dynamixel-sdk-examples-dbgsym

ros-foxy-dynamic-edt-3d                          ros-foxy-dynamixel-sdk
ros-foxy-dynamic-edt-3d-dbgsym                   ros-foxy-dynamixel-sdk-custom-interfaces
ros-foxy-dynamic-graph                           ros-foxy-dynamixel-sdk-custom-interfaces-dbgsym
ros-foxy-dynamic-graph-dbgsym                    ros-foxy-dynamixel-sdk-dbgsym
ros-foxy-dynamixel-hardware-interface            ros-foxy-dynamixel-sdk-examples
ros-foxy-dynamixel-hardware-interface-dbgsym     ros-foxy-dynamixel-sdk-examples-dbgsym
`

apperently ros-galactic-dynamixel-hardware-interface doesn't exist!!!

any ideas how to fix this?

**Comment by ROBOTIS-Will** [comment]
Hi @3mrrrx 

Since this issue is being discussed in the original repository, I'll close this thread.
https://github.com/youtalk/dynamixel_control/issues/15
Thanks!
