### ISSUE TITLE
XC-330-T288-T support

### ISSUE THREAD

**Issue by palwanishan** [ROBOTIS-GIT/dynamixel-workbench#348]
I want utilize XC-330-T288-T as manipulator gripper servo and control with ROS. But dynamixel_workbench doesn't support this model somehow. 

rosrun dynamixel_workbench_controllers find_dynamixel /dev/ttyUSB0

This command gives me result in below:

id : 28, model name : (null)
id : 29, model name : (null)

Instead of (null) it is supposed to print the model name such as XC-330-T288-T.

To be specific I modified my Open-manipulator-X and made it 7-dof including E.E. with XC-330-T288-T.

**Comment by ROBOTIS-Will** [comment]
Hi @palwanishan 

I'm sorry about the delayed response.
The X330 series has been updated in the `develop` branch #349.
Please try with it and let us know if it works for you.
Once I get a confirmation from you, I'll merge it into the master.
Thanks!

**Comment by palwanishan** [comment]
Greetings! I appreciate your response. 
I did exactly you told and here is progress. Now dynamixel_workbench recognizing XC-330. 

But still have some problem:

[ERROR] [DynamixelWorkbench] Failed to set velocity based profile!
[ERROR] [DynamixelTool] Can't find Item
[ERROR] [DynamixelWorkbench] Failed to change torque status!

I attached screen captures as well.

I'm using ROS-Noetic

Thanks!

![Screenshot from 2021-12-07 19-12-44](https://user-images.githubusercontent.com/77519615/145013658-bc1ecf77-545f-4242-b8bb-a9c06979b3b0.png)
![Screenshot from 2021-12-07 19-13-35](https://user-images.githubusercontent.com/77519615/145013660-a6f87df8-24b5-49fc-bf5e-6bcf32ad667f.png)
![Screenshot from 2021-12-07 19-34-44](https://user-images.githubusercontent.com/77519615/145013662-b0dc790c-9618-4e7e-9761-f267d6cc2c07.png)

**Comment by palwanishan** [comment]
I looked up source code and copy pasted 1 line and it's working now.

dynamixel_item.cpp - 
const ControlItem *DynamixelItem::getControlTable(uint16_t model_number) {
else if (num == XL330_M077 || num == XL330_M288 || num == XC330_M181 || num == XC330_M288 || num == XC330_T181 || num == XC330_T288)}

previously it was - 

const ControlItem *DynamixelItem::getControlTable(uint16_t model_number) {
else if (num == XL330_M077 || num == XL330_M288)}

Thanks!

**Comment by ROBOTIS-Will** [comment]
Oh, thanks for testing and reviewing the code.
I've appended the missing models in the getControlTable function and committed to the `develop` branch(#349).
I'll merge and release this update for melodic and noetic within a couple weeks.
Thank you!
