### ISSUE TITLE
dynamixel_sdk/dynamixel_sdk.h: No such file or directory

### ISSUE THREAD

**Issue by ameykore** [ROBOTIS-GIT/dynamixel-workbench#356]
Hello,
I following instruction on [this](https://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_workbench/) website to run Dynamixel XL330-M288-T. but whenever I run cmake command I get following error: -
`29:12: fatal error: dynamixel_sdk/dynamixel_sdk.h: No such file or directory
   29 |   #include "dynamixel_sdk/dynamixel_sdk.h"
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.`

Can anyone help me with this. Thank you in advance.

**Comment by ROBOTIS-Will** [comment]
Hi @ameykore 

Please let us know more details about your development environment and describe the steps to reproduce the issue.
Information in this reply is based on assumptions below :
1. You are running ROS Noetic on Linux.
2. DYNAMIXEL is connected to the PC via U2D2
3. DYNAMIXEL Workbench package source code was correctly downloaded under the `~/catkin_ws/src` directory and built using `git clone ...` and `cmake` commands.

The DYNAMIXEL Workbench package requires DYNAMIXEL SDK package as a dependent.
If you cloned the DYNAMIXEL Workbench source code and built from it, the SDK may not have been installed correctly.
Please use the command below and replace the {ROS-VERSION} with the one that you are actually using such as `kinetic`.
```bash
$ sudo apt install ros-{ROS-VERSION}-dynamixel-sdk
```

Thanks
