### ISSUE TITLE
dynamixel_workbench_toolbox fails to install 

### ISSUE THREAD

**Issue by tfoote** [ROBOTIS-GIT/dynamixel-workbench#39]
```
dynamixel-workbench-toolbox/opt/ros/kinetic/include/dynamixel_workbench_toolbox/dynamixel_tool.h
17:38:40 CMake Error at cmake_install.cmake:75 (file):
17:38:40   file INSTALL cannot find
17:38:40   "/tmp/binarydeb/ros-kinetic-dynamixel-workbench-toolbox-0.1.4/dynamixel_workbench_toolbox".
17:38:40 
17:38:40 
```
http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__dynamixel_workbench_toolbox__ubuntu_xenial_amd64__binary/19/console

Rolling back the release to fix the Kinetic build: https://github.com/ros/rosdistro/pull/14846

**Comment by routiful** [comment]
Hi :)

I have a mistake. So, I modified install code in cmake file. 
It will be updated master branch.

Thanks.
