### ISSUE TITLE
Difference from dynamixel_controllers

### ISSUE THREAD

**Issue by jysung** [ROBOTIS-GIT/dynamixel-workbench#41]
Is there a documentation regarding a difference between this package and dynamixel_controllers package? 
http://wiki.ros.org/dynamixel_controllers/Tutorials

I am trying to build a robot with Dynamixel MX-12W motors but confused as to which one I should be using. Do these packages offer similar or same functionalities? What are differences between two packages?

**Comment by routiful** [comment]
Hi :)

I reply some question in [ROS ANSWERS](http://answers.ros.org/question/261887/which-dynamixel-package-shoud-be-used/?answer=261983#post-id-261983) It can help your questions.

Thanks.

**Comment by jysung** [comment]
Thank you for answering my question!
