### ISSUE TITLE
There is no dynamixel_sdk in the package

### ISSUE THREAD

**Issue by Juna2** [ROBOTIS-GIT/dynamixel-workbench#54]
I git clone the dynamixel-workbench and did catkin_make and I got error.
It said there is no dynamixel_sdk so I downloaded it and the problem solved.
Is there something that I missed?
And after that I got another error. It said

.
.
.
-- ==> add_subdirectory(dynamixel-workbench/dynamixel_workbench_controllers)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'dynamixel_workbench_single_manager'
-- ==> add_subdirectory(dynamixel-workbench/dynamixel_workbench_single_manager)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'dynamixel_workbench_single_manager_gui'
-- ==> add_subdirectory(dynamixel-workbench/dynamixel_workbench_single_manager_gui)
CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "qt_build" with any
  of the following names:

    qt_buildConfig.cmake
    qt_build-config.cmake

  Add the installation prefix of "qt_build" to CMAKE_PREFIX_PATH or set
  "qt_build_DIR" to a directory containing one of the above files.  If
  "qt_build" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  dynamixel-workbench/dynamixel_workbench_single_manager_gui/CMakeLists.txt:10 (find_package)

-- Could not find the required component 'qt_build'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "qt_build" with any
  of the following names:

    qt_buildConfig.cmake
    qt_build-config.cmake

  Add the installation prefix of "qt_build" to CMAKE_PREFIX_PATH or set
  "qt_build_DIR" to a directory containing one of the above files.  If
  "qt_build" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  dynamixel-workbench/dynamixel_workbench_single_manager_gui/CMakeLists.txt:10 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/juna/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/juna/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

so I erase the 'dynamixel_workbench_single_manager_gui' folder(package) and then catkin_make successfully done.
but I would like to know how to solve the problem without erase the folder.
Thanks in advance!

**Comment by routiful** [comment]
Hi :)

Sorry, I didn't notice dependent package for launching dynamixel-workbench-single-manager-gui
This command will help you and i add section in [WIKI](http://wiki.ros.org/dynamixel_workbench)

$ sudo apt-get install ros-kinetic-qt-build

Thanks.
