### ISSUE TITLE
Dynamixel AX 12A Servo trouble

### ISSUE THREAD

**Issue by uyeolmakistemiyodum** [ROBOTIS-GIT/dynamixel-workbench#63]
Hello, 

I have a system that consists of three servos atthached. The first two servos are working. When I attach the third servo it works for once then stops working. I tried it with two new bought servos. All are AX-12A. One of the servos that I tried for the third one is blinking the red led and the other just keeps lighting the red led continously. I tried to make a firmware recovery shutting the power supply obviously and they still didn't work. What are the error codes and what can I do to fix it?

Thank you.

**Comment by routiful** [comment]
Hi :)

Would you tell me which package do you use? 
'dynamixel_workbench_single_manager' launches with single Dynamixel and
'dynamixel_workbench_controller' launches with two Dynamixel.

'dynamixel-workbench' does not provide examples for three connected Dynamixel.
But you can get reference for it in '[open-manipulator](https://github.com/ROBOTIS-GIT/open_manipulator.git)' packages. It uses five Dynamixel with 'dynamixel_workbench_toolbox'

Thanks.
Darby
