### ISSUE TITLE
Torque control 

### ISSUE THREAD

**Issue by xonak** [ROBOTIS-GIT/dynamixel-workbench#65]
Hello, 

Does the Torque_Control package only support the XM430 - W350 - R? 
I would like to use XM430 - W210 - R.

Is there any way?

**Comment by routiful** [comment]
Hi :)

torque_control node supports XM series.
But parameters(p_gain and d_gain) in launch file is set for XM430-W350.
If you want to use other Dynamixels, you need to adjust the parameters.

Thanks.
Darby

**Comment by xonak** [comment]
Thanks.
