### ISSUE TITLE
Error: There is no stasus packet!

### ISSUE THREAD

**Issue by Ash1020** [ROBOTIS-GIT/dynamixel-workbench#67]
Hi,
I am trying to controll Dynamixel MX-64 (protocol 1.0) by using Ubuntu 14.04 and ROS Indigo, so I followed to dynamixel_workbench_single_manager tutorials.
I succeed to connect to dynamixel and can manage that, but Error had occered suddenly, then I became to be NOT able to control anymore.

The message below,
This function is deprecated. Use 'printf()' and 'getRxPacketError()' instead
[TxRxResult] There is no status packet!
[ERROR] [1504063938.132737040]: [ID] 30, Fail to read!(status_return_level)

This message had displayed and loop with changing the commands what inside (), until I kill and exit this launch file.

What are these errors and how can I possibly fix them?

Thanks

**Comment by routiful** [comment]
Hi :)

Did you update MX-64 firmware?

**Comment by Ash1020** [comment]
No, I didn't. 
I'll try it.
How can I update that firmware?

**Comment by routiful** [comment]
You need to download ROBOPLUS[(link)](http://en.robotis.com/BlueAD/board.php?bbs_id=downloads&mode=view&bbs_no=1152561&page=1&key=&keyword=&sort=&scate=)
It helps update MX-64's firmware and test it in.

Thanks
Darby

**Comment by orasman** [comment]
Hi~
you need to check you have connecting more than one dynamixel at the same time. i have same error when i connect one more motor.

**Comment by routiful** [comment]
Thats' right. Thank you @orasman :)
