### ISSUE TITLE
Latency of dynamixel RX-24F

### ISSUE THREAD

**Issue by Angit16** [ROBOTIS-GIT/dynamixel-workbench#72]
Hi,
I have looked into many packages other than this one regarding how to play with dynamixel servos.
I am still unclear about the latency of individual dynamixel. Can you please provide some information?
In addition, I want to know about return delay as well. According to the dynamixel manuals, based on the Buadrate return delay time changes. How is it related to different size of data packets that one would like to read or write?

thanks,

**Comment by routiful** [comment]
Sorry. I am business trip now. I will check your issue as soon as possible.

**Comment by routiful** [comment]
Hi :) 

You can get an information about return delay time in [E-Manual](http://support.robotis.com/en/)
Following below 
<kbd>http://support.robotis.com/en/</kbd> -> <kbd>Product Information</kbd> -> <kbd>Actuator</kbd> -> <kbd>Dynamixel X</kbd> -> <kbd>XM Series</kbd> -> <kbd>XM430-W350</kbd> -> <kbd>Return Delay Time</kbd>

Thanks
Darby
