### ISSUE TITLE
mx 106 T protocol 2.0

### ISSUE THREAD

**Issue by elthef** [ROBOTIS-GIT/dynamixel-workbench#74]
I have problem trying to use workbench example with mx 106 T. I have I have error on not able to detect.
Do I need to change anything for it to work?
Thank you

**Comment by routiful** [comment]
Hi :)
MX-106 T is working fine using workbench_single_manager. 
I recommend you need to check firmware version using [ROBOTIS ROBOPLUS 1.0](http://en.robotis.com/BlueAD/board.php?bbs_id=downloads&mode=view&bbs_no=1152561&page=1&key=&keyword=&sort=&scate=)
and id, baudrate.

Thanks
Darby
