### ISSUE TITLE
Position controller for 1 single Dynamixel

### ISSUE THREAD

**Issue by christophebedard** [ROBOTIS-GIT/dynamixel-workbench#76]
I want to control 3 Dynamixels, but the `position_control` node is set up for pan+tilt. I want one controller that can be instantiated for every Dynamixel I have (given different/unique IDs). `single_dynamixel_controller` doesn't seem like it's made for this either.

I can't seem to find what I want. Does it exist?

**Comment by christophebedard** [comment]
#60 seemed to ask for the same thing
> Is there an out-of-the box solution to spawn one controller for each dynamixel plugged on /dev/ttyUSB0?

**Comment by routiful** [comment]
[OpenManipulator](https://github.com/ROBOTIS-GIT/open_manipulator/tree/master/open_manipulator_dynamixel_ctrl) uses dynamixel workbench to control 5 dynamixel.
This example will help you.

Thanks
Darby

**Comment by christophebedard** [comment]
Looks great, thank you!
