### ISSUE TITLE
Can I lanuch two position controllers with one USB2Dynamixel?

### ISSUE THREAD

**Issue by alanypf** [ROBOTIS-GIT/dynamixel-workbench#82]
I have 4 AX-12A servos and would like to divide them into two groups. So I tried to launch two position controllers and each controller controls 2 servos like the tutorial.  I changed the servo ID and node name. I can launch the first controller.However, when I launched the second position controller they both died for some reason. Is there something I am missing or I just could not launch two position controllers.  
Thanks for your help.

**Comment by routiful** [comment]
Hi :)

position controller is example for only 2 dynamixel.
OpenManipulator uses dynamixel workbench to control 5 dynamixel.
This example will help you.

Thanks
Darby
