### ISSUE TITLE
clock drift of dynamixel Rx-24F

### ISSUE THREAD

**Issue by Angit16** [ROBOTIS-GIT/dynamixel-workbench#91]
Hi, 
I need to know whether the time stamp of Dynamixel RX-24F comes from the hardware clock or derived from the return delay time with the help of system time (PC clock)?
thanks,

**Comment by ROBOTIS-Leon** [comment]
@Angit16 

Hi, nice to see you here
and sorry for the late

if you mean the realtime_tick which is shown by the dynamixel_workbench_single_manager, it is come from the dynamixel tick, and if it isn't what you mean, it comes from the computer

which app are you using now?
