### ISSUE TITLE
Please Check USB Port authorization and Baudrate [ex : 57600, 115200, 1000000, 3000000]

### ISSUE THREAD

**Issue by YuehChuan** [ROBOTIS-GIT/dynamixel-workbench#94]
Hello Dorby and Leon,
I'm using  AX-12A with U2D2 new connector.
This is ma hardware configuration.
![img_7378](https://user-images.githubusercontent.com/7314531/34058182-0244d508-e215-11e7-8b91-9600d6284131.JPG)

follow this.
http://wiki.ros.org/dynamixel_workbench_single_manager/Tutorials/GUI
Build from source and when I want open  GUI to  set motor ID . 

shows
![dynamixel_error](https://user-images.githubusercontent.com/7314531/34055748-8fc5106e-e20b-11e7-8519-db51e2e1511f.png)

```bash
process[single_dynamixel_monitor-2]: started with pid [7149]
[ INFO] [1513363628.617394991]: Succeeded to open the port(/dev/ttyUSB0)!
[ INFO] [1513363628.624420877]: Succeeded to change the baudrate(57600)!
[ INFO] [1513363628.624483780]: Scan Dynamixel(ID: 1~253) Using Protocol 2.0

[ INFO] [1513363628.624540752]: ...wait for seconds
[ WARN] [1513363633.662755955]: Please Check USB Port authorization and
[ WARN] [1513363633.662802262]: Baudrate [ex : 57600, 115200, 1000000, 3000000]
[ERROR] [1513363633.662828001]: ...Failed to find dynamixel!
================================================================================REQUIRED process [single_dynamixel_monitor-2] has died!
process has died [pid 7149, exit code -11, cmd /home/schwarm/techman/catkin_ws/devel/lib/dynamixel_workbench_single_manager/single_dynamixel_monitor __name:=single_dynamixel_monitor __log:=/home/schwarm/.ros/log/5a270a90-e1c8-11e7-8e7e-0811961618c4/single_dynamixel_monitor-2.log].
log file: /home/schwarm/.ros/log/5a270a90-e1c8-11e7-8e7e-0811961618c4/single_dynamixel_monitor-2*.log
Initiating shutdown!
================================================================================
[single_dynamixel_monitor-2] killing on exit

```

Any hint?
TQ in advance!

**Comment by ROBOTIS-Leon** [comment]
@YuehChuan 

Long time no see,

you are using AX series, right?
it can't be controlled with `Protocol 2.0 comm packet`

Change here to `1.0`:
https://github.com/ROBOTIS-GIT/dynamixel-workbench/blob/399cceb071283e58055a7f0db14a5b6636892a22/dynamixel_workbench_single_manager/launch/single_manager.launch#L7

and check also if the baudrate and id are set properly.

**Comment by YuehChuan** [comment]
yes, AX-12A. I will try it. TQ!

**Comment by YuehChuan** [comment]
I get no luck
![dynamixel-a](https://user-images.githubusercontent.com/7314531/34456262-5137d188-edcd-11e7-878e-c79452d39caf.png)
and this is running dynamixelSDK read_write example
![dynamixel](https://user-images.githubusercontent.com/7314531/34456268-5cdccad4-edcd-11e7-8a36-8831bd1dd268.png)

**Comment by YuehChuan** [comment]
get no luck
![dynamixel-a](https://user-images.githubusercontent.com/7314531/34456328-97bef0cc-edce-11e7-8d54-1edc64cb313f.png)
and this is SDK 
![dynamixel](https://user-images.githubusercontent.com/7314531/34456338-b44e64ca-edce-11e7-962d-b49ad4ac2da4.png)
read_write example output

**Comment by routiful** [comment]
Hi @YuehChuan 

Sorry for late answer. 
Did you launch it different baudrate??
AX series has default 1M baudrate.

**Comment by ROBOTIS-Leon** [comment]
@routiful 

He think that his AX has a problem,
let's wait for his response

**Comment by YuehChuan** [comment]
@routiful  @ROBOTIS-Leon  TQ! I will update here if any progress!

**Comment by routiful** [comment]
Hi @YuehChuan 

Do you solve this problem??

**Comment by routiful** [comment]
This issue will be closed since there were no actions for a while.
You can reopen this issue to show this issue to the users whenever.
Thanks. :)

**Comment by RishavGH** [comment]
I am having the same problem. Please tell me how to solve this problem. I have tried after changing the protocol but it doesn't work the next time I connect the motor.
