### ISSUE TITLE
Fail to read dynamixels after updating firmware

### ISSUE THREAD

**Issue by vftejada** [ROBOTIS-GIT/dynamixel-workbench#95]
Hello, I recently updated firmware on dynamixels MX-28, MX-64, MX-64AT and MX-106 getting the following error for them all:

started roslaunch server http://fieldworkrobotics-P64V7:32869/

SUMMARY
========

PARAMETERS
 * /baud_rate: 57600
 * /device_name: /dev/ttyUSB0
 * /ping: False
 * /ping_id: 1
 * /protocol_version: 2.0
 * /rosdistro: kinetic
 * /rosversion: 1.12.7

NODES
  /
    single_dynamixel_monitor (dynamixel_workbench_single_manager/single_dynamixel_monitor)

auto-starting new master
process[master]: started with pid [15446]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 825dc292-ec9a-11e7-97c4-14abc52a330c
process[rosout-1]: started with pid [15459]
started core service [/rosout]
process[single_dynamixel_monitor-2]: started with pid [15468]
[ INFO] [1514553401.894273619]: Succeeded to open the port(/dev/ttyUSB0)!
[ INFO] [1514553401.899031115]: Succeeded to change the baudrate(57600)!
[ INFO] [1514553401.899081224]: Scan Dynamixel(ID: 1~253) Using Protocol 2.0

[ INFO] [1514553401.899117085]: ...wait for seconds
[ERROR] [1514553401.926550339]: Unable to open .device file : /home/fieldworkrobotics/Virginia/catkin_ws_PhD/src/dynamixel-workbench/dynamixel_workbench_toolbox/dynamixel/models//.device
================================================================================REQUIRED process [single_dynamixel_monitor-2] has died!
process has finished cleanly
log file: /home/fieldworkrobotics/.ros/log/825dc292-ec9a-11e7-97c4-14abc52a330c/single_dynamixel_monitor-2*.log
Initiating shutdown!
================================================================================
[single_dynamixel_monitor-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

Code downloaded from source in Github and working like a charm with the old firmware

**Comment by routiful** [comment]
Hi @vftejada  :)

Dynamixel workbench in master branch don't support MX (2.0). 
If you want to use it, you have to add dynamixel information in toolbox library.
The next version of workbench will be released next month. It will be support MX(2.0)

Thanks
Darby
